In [3]:
%run EDA.ipynb

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3750 entries, 0 to 3749
Columns: 10000 entries, 0 to 9999
dtypes: float64(10000)
memory usage: 286.1 MB
number of duplicate rows:  (0, 10000)

,0,1,2,3,4,5,6,7,8,9,...,9990,9991,9992,9993,9994,9995,9996,9997,9998,9999
count,3750.000000,3750.000000,3750.000000,3750.000000,3750.000000,3750.000000,3750.000000,3750.000000,3750.000000,3750.000000,...,3750.000000,3750.000000,3750.000000,3750.000000,3750.000000,3750.000000,3750.000000,3750.000000,3750.000000,3750.000000
mean,30.644135,9.080955,169.679419,811.083532,-186.008805,25.717789,24.918118,19.061259,14.826002,14.970447,...,13.997377,21.456582,22.586461,16.736889,13.992185,-1.426345,9.597250,-2.031243,-2.841237,38.071903
std,286.172414,213.166659,43665.003613,57123.457110,21942.466227,711.556331,898.109174,868.676044,532.727247,236.749501,...,269.223339,545.746530,265.221187,503.416444,818.825405,655.666258,204.731554,793.022407,629.128655,768.405732
min,-989.450000,-859.922000,-163336.428000,-243844.632000,-77566.109000,-2414.196000,-3227.681000,-3151.321000,-1792.781000,-794.271000,...,-957.937000,-1983.009000,-937.357000,-1758.858000,-2526.791000,-2165.769000,-739.205000,-2731.037000,-2223.909000,-2565.513000
25%,-163.781750,-135.343500,-29284.119500,-38028.429000,-14426.799500,-448.696750,-590.170250,-562.956500,-349.689750,-144.157750,...,-169.777250,-352.959500,-154.639750,-328.083750,-550.599000,-432.000750,-129.076250,-561.304000,-424.192750,-462.828000
50%,35.478500,2.680500,1181.698500,980.588000,-154.835000,13.931500,13.674000,16.750500,9.731000,11.159500,...,18.700000,38.348500,26.199500,14.575500,1.363500,-3.796500,8.600500,-4.243000,-7.628000,28.107000
75%,215.780500,156.095750,29630.914500,40561.960250,14515.833000,506.893250,630.490750,608.698000,383.110500,179.768250,...,196.049000,396.868500,198.237250,356.185500,574.453250,425.338000,149.855750,539.550000,427.794500,552.173500
max,1224.394000,722.868000,177744.241000,215372.854000,86287.955000,2446.466000,3118.087000,2966.971000,1914.308000,803.200000,...,893.196000,2080.750000,1070.453000,1705.664000,2868.989000,2562.331000,685.176000,3123.617000,2204.527000,2664.074000

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1250 entries, 0 to 1249
Columns: 10000 entries, 0 to 9999
dtypes: float64(10000)
memory usage: 95.4 MB
Number of duplicate rows:  (0, 10000)

,0,1,2,3,4,5,6,7,8,9,...,9990,9991,9992,9993,9994,9995,9996,9997,9998,9999
count,1250.000000,1250.000000,1250.000000,1250.000000,1250.000000,1250.000000,1250.000000,1250.000000,1250.000000,1250.000000,...,1250.000000,1250.000000,1250.000000,1250.000000,1250.000000,1250.000000,1250.000000,1250.000000,1250.000000,1250.000000
mean,6.892262,24.231871,691.035041,-923.186420,472.853216,-5.603389,-8.430038,18.087694,45.521371,5.532402,...,11.476222,33.046902,14.964225,1.617977,0.966285,27.937748,17.698405,-5.434074,2.335376,18.155565
std,279.865345,208.490530,43757.863316,57126.680674,21901.701715,713.053055,920.126198,878.797561,522.835391,228.835834,...,269.321713,545.254843,279.002383,484.089443,811.995519,668.026761,205.254268,795.507890,618.042044,777.694783
min,-1105.426000,-649.565000,-155113.836000,-184240.160000,-91291.593000,-2035.416000,-2908.191000,-2716.201000,-1637.602000,-841.328000,...,-754.360000,-2337.359000,-843.832000,-1660.371000,-3048.856000,-1897.451000,-656.654000,-2452.794000,-2080.857000,-2991.225000
25%,-176.906000,-116.729500,-27510.364750,-41059.084000,-13750.416000,-520.422750,-635.170750,-562.046500,-343.264000,-154.387000,...,-178.323000,-326.482750,-177.293750,-334.303250,-533.827500,-395.463000,-128.044750,-539.452750,-416.250500,-510.043500
50%,12.362000,20.508000,-444.999500,-397.729500,765.368500,-8.634000,38.824500,6.567500,42.814500,13.917000,...,12.929500,14.458000,18.659500,3.275500,-7.966500,26.660500,25.876000,11.653000,-1.106000,26.721500
75%,185.231250,171.514250,31295.237500,36278.893000,14594.061750,493.204250,625.198250,613.078500,406.646750,161.198250,...,199.985000,381.024250,205.077500,335.198500,573.268250,465.582000,157.331750,548.572500,424.111750,554.481750
max,1053.495000,736.906000,141244.534000,177561.749000,60844.690000,2397.488000,2987.201000,2916.440000,1765.077000,684.350000,...,1093.874000,2010.261000,914.288000,1647.605000,2444.526000,2412.412000,610.140000,2354.781000,1989.205000,2157.461000

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3750 entries, 0 to 3749
Data columns (total 1 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   0       3750 non-null   int64
dtypes: int64(1)
memory usage: 29.4 KB

In [4]:
%run Upsampling.ipynb

Upsampling minority class
Len of minor class is: 267
 and major class: 2358

In [5]:
from sklearn import svm
from sklearn.svm import SVC
from sklearn.pipeline import Pipeline
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import accuracy_score
from sklearn.decomposition import KernelPCA

In [6]:
svc = SVC()
C = np.logspace(0, 4, 10)
kernel = ['linear', 'rbf', 'poly']
gamma = ['scale', 'auto']
class_weight = [None, 'balanced']
max_iter = [1]

pipe = Pipeline([('StandardScaler', StandardScaler()), ('PCA', PCA(0.95)), ("classifier", svc)])
hyperparameters = dict(C=C, class_weight=class_weight, gamma=gamma, kernel=kernel, max_iter=max_iter)

In [7]:
gridsearch = GridSearchCV(svc, hyperparameters, cv=5, verbose=1, n_jobs=-1)

In [8]:
display("HYPERPARAMETERS")
display(hyperparameters)

display("SVC PARAMETERS")
display(svc.get_params().keys())

display("GRIDSEARCH STEPS")
display(gridsearch)

'SVC PARAMETERS'

dict_keys(['C', 'break_ties', 'cache_size', 'class_weight', 'coef0', 'decision_function_shape', 'degree', 'gamma', 'kernel', 'max_iter', 'probability', 'random_state', 'shrinking', 'tol', 'verbose'])

'GRIDSEARCH STEPS'

GridSearchCV(cv=5, estimator=SVC(), n_jobs=-1,
             param_grid={'C': array([1.00000000e+00, 2.78255940e+00, 7.74263683e+00, 2.15443469e+01,
       5.99484250e+01, 1.66810054e+02, 4.64158883e+02, 1.29154967e+03,
       3.59381366e+03, 1.00000000e+04]),
                         'class_weight': [None, 'balanced'],
                         'gamma': ['scale', 'balanced'],
                         'kernel': ['linear', 'rbf', 'poly'], 'max_iter': [1]},
             verbose=1)

In [9]:
best_model = gridsearch.fit(upsampled_X, np.ravel(upsampled_y.T))

Fitting 5 folds for each of 120 candidates, totalling 600 fits

C:\Miniconda\envs\pythonProject\lib\site-packages\sklearn\model_selection\_search.py:922: UserWarning: One or more of the test scores are non-finite: [0.50466641 0.48154982 0.49894045        nan        nan        nan
 0.50466641 0.50000157 0.50063717        nan        nan        nan
 0.50466641 0.50466641 0.50212067        nan        nan        nan
 0.50466641 0.50466641 0.50212067        nan        nan        nan
 0.50466641 0.50466641 0.50212067        nan        nan        nan
 0.50466641 0.50466641 0.50212067        nan        nan        nan
 0.50466641 0.50466641 0.50212067        nan        nan        nan
 0.50466641 0.50466641 0.50212067        nan        nan        nan
 0.50466641 0.50466641 0.50212067        nan        nan        nan
 0.50466641 0.50466641 0.50212067        nan        nan        nan
 0.50466641 0.50466641 0.50212067        nan        nan        nan
 0.50466641 0.50466641 0.50212067        nan        nan        nan
 0.50466641 0.50466641 0.50212067        nan        nan        nan
 0.50466641 0.50466641 0.50212067        nan        nan        nan
 0.50466641 0.50466641 0.50212067        nan        nan        nan
 0.50466641 0.50466641 0.50212067        nan        nan        nan
 0.50466641 0.50466641 0.50212067        nan        nan        nan
 0.50466641 0.50466641 0.50212067        nan        nan        nan
 0.50466641 0.50466641 0.50212067        nan        nan        nan
 0.50466641 0.50466641 0.50212067        nan        nan        nan]
  warnings.warn(
C:\Miniconda\envs\pythonProject\lib\site-packages\sklearn\svm\_base.py:255: ConvergenceWarning: Solver terminated early (max_iter=1).  Consider pre-processing your data with StandardScaler or MinMaxScaler.
  warnings.warn('Solver terminated early (max_iter=%i).'

In [10]:
best_model.best_score_

0.504666409044341

In [11]:
best_model.best_params_

{'C': 1.0,
 'class_weight': None,
 'gamma': 'scale',
 'kernel': 'linear',
 'max_iter': 1}